services:
  - type: web
    name: nciipc-supervisory-analytics
    runtime: node
    plan: free
    buildCommand: ""
    startCommand: "node server.js"
    envVars:
      - key: PORT
        value: 3000
